# after-login-command = []

after-startup-command = [
  # 'exec-and-forget borders style=round active_color=0xFFFFFFFF width=6.0 hidpi=off',
  # 'exec-and-forget sketchybar'
]

exec-on-workspace-change = ['/bin/bash', '-c',
  'sketchybar --trigger aerospace_workspace_change FOCUSED_WORKSPACE=$AEROSPACE_FOCUSED_WORKSPACE'
]

start-at-login = true

# Normalizations. See: https://nikitabobko.github.io/AeroSpace/guide#normalization
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

# See: https://nikitabobko.github.io/AeroSpace/guide#layouts
# The 'accordion-padding' specifies the size of accordion padding
# You can set 0 to disable the padding feature
accordion-padding = 300

# Possible values: tiles|accordion
default-root-container-layout = 'tiles'

# Possible values: horizontal|vertical|auto
# 'auto' means: wide monitor (anything wider than high) gets horizontal orientation,
#               tall monitor (anything higher than wide) gets vertical orientation
default-root-container-orientation = 'auto'

# Mouse follows focus when focused monitor changes
# Drop it from your config, if you don't like this behavior
# See https://nikitabobko.github.io/AeroSpace/guide#on-focus-changed-callbacks
# See https://nikitabobko.github.io/AeroSpace/commands#move-mouse
# Fallback value (if you omit the key): on-focused-monitor-changed = []
# on-focused-monitor-changed = ['move-mouse window-force-center']
# on-focused-window-changed = ['move-mouse window-force-center']
# move-mouse --fail-if-noop window-lazy-center || aerospace move-mouse monitor-lazy-center

# You can effectively turn off macOS "Hide application" (cmd-h) feature by toggling this flag
# Useful if you don't use this macOS feature, but accidentally hit cmd-h or cmd-alt-h key
# Also see: https://nikitabobko.github.io/AeroSpace/goodies#disable-hide-app
automatically-unhide-macos-hidden-apps = false

[[on-window-detected]]
if.app-name-regex-substring = 'system settings'
run = 'layout floating'

[[on-window-detected]]
if.app-name-regex-substring = 'finder'
run = 'layout floating'

[[on-window-detected]]
if.app-name-regex-substring = 'vnc viewer'
run = 'layout floating'

[[on-window-detected]]
if.app-name-regex-substring = 'utm'
run = 'layout floating'

# Possible values: (qwerty|dvorak|colemak)
# See https://nikitabobko.github.io/AeroSpace/guide#key-mapping
[key-mapping]
    preset = 'qwerty'

[gaps]
    inner.horizontal = 10
    inner.vertical =   10
    outer.left =       10
    outer.bottom =     10
    outer.top =        30 # set to '50' when using sketchybar
    outer.right =      10

[mode.main.binding]

    alt-period = 'layout tiles horizontal vertical'
    alt-comma = 'layout accordion horizontal vertical'

    alt-h = 'focus left'
    alt-j = 'focus down'
    alt-k = 'focus up'
    alt-l = 'focus right'

    alt-shift-h = 'move left'
    alt-shift-j = 'move down'
    alt-shift-k = 'move up'
    alt-shift-l = 'move right'

    alt-minus = 'resize smart -50'
    alt-equal = 'resize smart +50'

    alt-q = 'workspace 1'
    alt-w = 'workspace 2'
    alt-e = 'workspace 3'
    alt-r = 'workspace 4'
    alt-t = 'workspace 5'
    alt-y = 'workspace 6'
    alt-u = 'workspace 7'
    alt-i = 'workspace 8'
    alt-o = 'workspace 9'
    alt-p = 'workspace 0'

    alt-shift-q = 'move-node-to-workspace 1'
    alt-shift-w = 'move-node-to-workspace 2'
    alt-shift-e = 'move-node-to-workspace 3'
    alt-shift-r = 'move-node-to-workspace 4'
    alt-shift-t = 'move-node-to-workspace 5'
    alt-shift-y = 'move-node-to-workspace 6'
    alt-shift-u = 'move-node-to-workspace 7'
    alt-shift-i = 'move-node-to-workspace 8'
    alt-shift-o = 'move-node-to-workspace 9'
    alt-shift-p = 'move-node-to-workspace 0'

    alt-ctrl-shift-f = 'fullscreen'
    # alt-ctrl-f = 'layout floating'

    alt-tab = 'workspace-back-and-forth'
    
    # alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'

    alt-shift-semicolon = 'mode service'

[mode.service.binding]
    esc = ['reload-config', 'mode main']
    r = ['flatten-workspace-tree', 'mode main'] # reset layout
    f = ['layout floating tiling', 'mode main'] # Toggle between floating and tiling layout
    backspace = ['close-all-windows-but-current', 'mode main']

    alt-shift-h = ['join-with left', 'mode main']
    alt-shift-j = ['join-with down', 'mode main']
    alt-shift-k = ['join-with up', 'mode main']
    alt-shift-l = ['join-with right', 'mode main']

    down = 'volume down'
    up = 'volume up'
    shift-down = ['volume set 0', 'mode main']
