
# tap repositories and their packages

tap homebrew/core
brew aom
brew argparse
brew aria2
brew aribb24
brew asitop
brew autoconf
brew autoconf-archive
brew automake
brew bash
brew bat
brew berkeley-db
brew berkeley-db@5
brew blake3
brew brotli
brew c-ares
brew ca-certificates
brew cabextract
brew cairo
brew cask
brew cbonsai
brew ccache
brew cdrtools
brew certifi
brew circumflex
brew cjson
brew cmake
brew cmatrix
brew coreutils
brew cpanminus
brew dav1d
brew deno
brew emacs
brew exiftool
brew ffmpeg
brew ffmpeg@6
brew flac
brew fmt
brew fontconfig
brew fontforge
brew freetype
brew frei0r
brew fribidi
brew fzf
brew gdbm
brew gdk-pixbuf
brew gettext
brew gh
brew giflib
brew git
brew glib
brew gmp
brew gnutls
brew graphite2
brew harfbuzz
brew helix
brew highway
brew hiredis
brew icu4c@77
brew icu4c@78
brew imagemagick
brew imath
brew imlib2
brew jasper
brew jpeg-turbo
brew jpeg-xl
brew jq
brew lame
brew lazygit
brew ldns
brew leptonica
brew less
brew libarchive
brew libass
brew libb2
brew libbluray
brew libcaca
brew libcbor
brew libde265
brew libdeflate
brew libevent
brew libfido2
brew libgit2
brew libheif
brew libice
brew libiconv
brew libidn2
brew liblqr
brew libmicrohttpd
brew libnghttp2
brew libnghttp3
brew libngtcp2
brew libogg
brew libomp
brew libpng
brew libraw
brew librist
brew librsvg
brew libsamplerate
brew libsm
brew libsndfile
brew libsodium
brew libsoxr
brew libspiro
brew libssh
brew libssh2
brew libtasn1
brew libtiff
brew libtool
brew libudfread
brew libultrahdr
brew libunibreak
brew libuninameslist
brew libunistring
brew libuv
brew libvidstab
brew libvmaf
brew libvorbis
brew libvpx
brew libx11
brew libxau
brew libxcb
brew libxdmcp
brew libxext
brew libxmu
brew libxrender
brew libxt
brew libyaml
brew libzip
brew little-cms2
brew lld@20
brew llvm@18
brew llvm@20
brew lpeg
brew lua
brew luajit
brew luarocks
brew luv
brew lz4
brew lzo
brew m4
brew mbedtls@3
brew mpdecimal
brew mpg123
brew nasm
brew ncurses
brew neovim
brew nettle
brew ninja
brew node
brew oniguruma
brew opencore-amr
brew openexr
brew openjpeg
brew openjph
brew openssh
brew openssl@1.1
brew openssl@3
brew opus
brew p11-kit
brew pango
brew pcre2
brew perl
brew pipes-sh
brew pipx
brew pixman
brew pkgconf
brew pnpm
brew python-packaging
brew python@3.12
brew python@3.13
brew python@3.14
brew pyvim
brew rav1e
brew rbenv
brew readline
brew ripgrep
brew rubberband
brew ruby
brew ruby-build
brew sdl2
brew sevenzip
brew shared-mime-info
brew simdjson
brew six
brew sl
brew snappy
brew speedtest-cli
brew speex
brew sqlite
brew srt
brew stow
brew svt-av1
brew telnet
brew tesseract
brew theora
brew tldr
brew toilet
brew tree-sitter
brew tree-sitter-cli
brew tree-sitter@0.25
brew unbound
brew unibilium
brew utf8proc
brew uvwasi
brew vim
brew viu
brew vulkan-headers
brew vulkan-loader
brew watch
brew webp
brew wget
brew wimlib
brew woff2
brew x264
brew x265
brew xclip
brew xorgproto
brew xvid
brew xxhash
brew xz
brew yarn
brew yt-dlp
brew zeromq
brew zig
brew zimfw
brew zimg
brew zsh-syntax-highlighting
brew zstd

tap homebrew/cask
cask 1password
cask appcleaner
cask balenaetcher
cask brave-browser
cask cool-retro-term
cask coteditor
cask daisydisk
cask datagrip
cask dbeaver-community
cask discord
cask fastmail
cask font-hack-nerd-font
cask font-jetbrains-mono-nerd-font
cask hyperkey
cask iina
cask istat-menus
cask logi-options+
cask macdown
cask microsoft-auto-update
cask microsoft-teams
cask proton-pass
cask protonvpn
cask qlmarkdown
cask raspberry-pi-imager
cask raycast
cask rustdesk
cask stremio
cask tor-browser
cask visual-studio-code
cask zed

tap 1password/tap

tap felixkratz/formulae
brew borders

tap jandedobbeleer/oh-my-posh

tap koekeishiya/formulae

tap nikitabobko/tap
cask aerospace

tap pomdtr/tap

tap rcmdnk/file
brew brew-file

tap sidneys/homebrew

# Other Homebrew packages
brew python-psutil

# App Store applications
appstore 937984704 Amphetamine (5.3.2)
appstore 1358823008 Flighty (4.7.3)
appstore 6698876601 Folder Preview (2.7)
appstore 1351639930 Gifski (2.23.1)
appstore 1622835804 Kagi for Safari (2.2.3)
appstore 6446206067 Klack (1.7.2)
appstore 441258766 Magnet (3.0.7)
appstore 985367838 Microsoft Outlook (16.104.1)
appstore 1482454543 Twitter (9.30)
appstore 1518836004 Video Converter (1.1.7)
appstore 310633997 WhatsApp (25.37.76)
