add_newline = false

palette = 'nord'

format = """
$directory\
$character\
"""
# $username\
# [@](nord8)$hostname\

right_format = """
$cmd_duration(bold nord13)\
$git_branch\
$git_status\
$golang\
$nodejs\
$python\
$docker_context\
"""

[character]
success_symbol = '[ \$](nord9)'
error_symbol = '[ \$](bold nord11)'
vimcmd_symbol = '[ <<~](bold nord14)'
vimcmd_replace_symbol = '[<<~](bold nord14)'
vimcmd_visual_symbol = '[V](bold nord13)'

[cmd_duration]
min_time = 500
format = '[took](nord15) [$duration](bold nord14)'

# [memory_usage]
# disabled = false
# threshold = -1
# symbol = ''
# style = 'bold nord14'

[username]
show_always = true
style_user = "nord14"
format = "[$user]($style)"

[hostname]
ssh_only = false
style = "nord15"
format = "[$hostname]($style)"
disabled = false
aliases = { "arch" = "arch" }

[directory]
style = "nord10"
format = " [$path]($style)"
truncate_to_repo = false
truncation_length = 3
fish_style_pwd_dir_length = 3
use_logical_path = true

[git_branch]
symbol = " 󰘬"
style = "nord7"
format = "[$symbol $branch]($style)"

[git_status]
style = "nord10"
format = '([\[$all_status$ahead_behind\]]($style))'

[os]
disabled = true

[rust]
disabled = true

[scala]
disabled = true

[c]
disabled = true

[elixir]
disabled = true

[elm]
disabled = true

[gradle]
disabled = true

[haskell]
disabled = true

[java]
disabled = true

[julia]
disabled = true

[nim]
disabled = true

[palettes.nord]
# polar night
nord0 = '#2e3440'
nord1 = '#3b4252'
nord2 = '#434c5e'
nord3 = '#4c566a'
# snow storm
nord4 = '#d8dee9'
nord5 = '#e5e9f0'
nord6 = '#eceff4'
# frost
nord7 = '#8fbcbb'
nord8 = '#88c0d0'
nord9 = '#81a1c1'
nord10 = '#5e81ac'
# aurora
nord11 = '#bf616a'
nord12 = '#d08770'
nord13 = '#ebcb8b'
nord14 = '#a3be8c'
nord15 = '#b48ead'
